# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."
  custom:
    android-debug-apk:
      - step:
          name: Android Debug Build APK
          image: ghcr.io/cirruslabs/flutter:3.22.0
          caches:
            - gradle
          script:
            - echo 'Fetching Dependencies'
            - flutter pub get

            - echo 'Building apk'
            - flutter build apk --debug --build-number=$VERSION_CODE --build-name=$VERSION_NAME --dart-define=BUGSNAG_API_KEY=$BUGSNAG_API_KEY --flavor prod

            - echo 'Archiving Artifacts'
            - mv build/app/outputs/flutter-apk/app-prod-debug.apk ./
          artifacts:
            - app-prod-debug.apk
    android-release-aab:
      - step:
          name: Android Release Build AAB
          image: ghcr.io/cirruslabs/flutter:3.22.0
          caches:
            - gradle
          script:
            - echo 'Fetching Dependencies'
            - flutter pub get

            - echo 'Retrieving secrets'
            - echo $KEYSTORE_B64 | base64 --decode > android/app/ueno-upload-keystore.jks
            - echo $KEY_PROPERTIES_B64 | base64 --decode > android/key.properties

            - echo 'Building App Bundle'
            - flutter build appbundle --release --build-number=$VERSION_CODE --build-name=$VERSION_NAME --dart-define=BUGSNAG_API_KEY=$BUGSNAG_API_KEY --flavor prod

            - echo 'Archiving Artifacts'
            - mv build/app/outputs/bundle/prodRelease/app-prod-release.aab ./
          artifacts:
            - app-prod-release.aab

