name: iOS Fastlane Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'User-facing release version name'
        required: true
        default: "1.0.0"
      versionCode:
        description: 'versionCode or build number'
        required: true
        default: '1'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

      - name: Build & upload iOS binary
        run: cd ios && bundle exec fastlane ios prepare_for_build
        env:
          ASC_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          ASC_KEY: ${{ secrets.$APPSTORE_PRIVATE_API_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.P12_PASSWORD }}
          SIGNING_KEY_FILE_PATH: signing-cert.p12

      - name: Build the app
        run: flutter build ipa --release --export-options-plist=ios/exportOptions.plist --build-number=${{ github.event.inputs.versionCode }} --build-name=${{ github.event.inputs.versionName }}

      - name: Upload to testflight
        run: cd ios && bundle exec fastlane ios upload_release
        env:
          ASC_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          ASC_KEY: ${{ secrets.$APPSTORE_PRIVATE_API_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.P12_PASSWORD }}
          SIGNING_KEY_FILE_PATH: signing-cert.p12
