name: New Android debug build

on:
  workflow_dispatch:
    inputs:
      tramline-input:
        required: false

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
    - name: Configure Tramline
      uses: tramlinehq/deploy-action@v0.1.3
      with:
        input: ${{ github.event.inputs.tramline-input }}

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        cache: 'gradle'

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.5'
        channel: 'stable' 
        cache: true

    # Get flutter dependencies.
    - run: flutter pub get
    
    - run: flutter --version
    
    # Build apk.
    - run: flutter build apk --debug --build-number=${{ github.event.inputs.versionCode }} --build-name=${{ github.event.inputs.versionName }}

    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v3
      with:
        name: release-aab
        path: build/app/outputs/flutter-apk/app-debug.apk
